const ActionsTypes = {
  USE_INGREDIENT:     'USE_INGREDIENT',
  DROP_INGREDIENT:    'DROP_INGREDIENT',
  FETCH_INGRIDIENTS:  'FETCH_INGRIDIENTS',
  RESET_INGRIDIENTS:  'RESET_INGRIDIENTS',
  ORDER_TOGGLE:       'ORDER_TOGGLE',
  ORDER_SUBMIT:       'ORDER_SUBMIT'
}

export default ActionsTypes